# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PostWCpp <- function(w, y, xAIDS, maxDTime, betaAIDS, kappa, bFE, varCovRE, baseCD4DM, fxCD4Data, baseVLDM, fxVLData, baseRandEffDM, fzData, err) {
    .Call(`_hivPlatform_PostWCpp`, w, y, xAIDS, maxDTime, betaAIDS, kappa, bFE, varCovRE, baseCD4DM, fxCD4Data, baseVLDM, fxVLData, baseRandEffDM, fzData, err)
}

IntegratePostWCpp <- function(lower, upper, y, xAIDS, maxDTime, betaAIDS, kappa, bFE, varCovRE, baseCD4DM, fxCD4Data, baseVLDM, fxVLData, baseRandEffDM, fzData, err) {
    .Call(`_hivPlatform_IntegratePostWCpp`, lower, upper, y, xAIDS, maxDTime, betaAIDS, kappa, bFE, varCovRE, baseCD4DM, fxCD4Data, baseVLDM, fxVLData, baseRandEffDM, fzData, err)
}

Lspline <- function(x, knots) {
    .Call(`_hivPlatform_Lspline`, x, knots)
}

GetLogMVNPdf <- function(x, mu, sigma) {
    .Call(`_hivPlatform_GetLogMVNPdf`, x, mu, sigma)
}

GetLogMVNPdf2 <- function(x, mu, sigma) {
    .Call(`_hivPlatform_GetLogMVNPdf2`, x, mu, sigma)
}

