# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Seq <- function(start, end) {
    .Call(`_hivPlatform_Seq`, start, end)
}

integrate_test <- function() {
    .Call(`_hivPlatform_integrate_test`)
}

PostWCpp <- function(w, y, z, xAIDS, maxDTime, betaAIDS, kappa, bFE, sigma2, varCovRE, fxCD4Data, fxVRData, fzData, consc, consr) {
    .Call(`_hivPlatform_PostWCpp`, w, y, z, xAIDS, maxDTime, betaAIDS, kappa, bFE, sigma2, varCovRE, fxCD4Data, fxVRData, fzData, consc, consr)
}

