// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// integrate_test
Rcpp::List integrate_test();
RcppExport SEXP _hivPlatform_integrate_test() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(integrate_test());
    return rcpp_result_gen;
END_RCPP
}
// PostWCpp
double PostWCpp(const double& w, const Rcpp::DataFrame& y, const Eigen::MatrixXd& xAIDS, const double& maxDTime, const Eigen::MatrixXd& betaAIDS, const double& kappa, const Eigen::MatrixXd& bFE, const Rcpp::NumericVector& sigma2, const Eigen::MatrixXd& varCovRE, const Rcpp::List& baseCD4DM, const Rcpp::DataFrame& fxCD4Data, const Rcpp::List& baseVLDM, const Rcpp::DataFrame& fxVLData, const Rcpp::List& baseRandEffDM, const Rcpp::DataFrame& fzData, const Rcpp::NumericVector& consc, const Rcpp::NumericVector& consr);
RcppExport SEXP _hivPlatform_PostWCpp(SEXP wSEXP, SEXP ySEXP, SEXP xAIDSSEXP, SEXP maxDTimeSEXP, SEXP betaAIDSSEXP, SEXP kappaSEXP, SEXP bFESEXP, SEXP sigma2SEXP, SEXP varCovRESEXP, SEXP baseCD4DMSEXP, SEXP fxCD4DataSEXP, SEXP baseVLDMSEXP, SEXP fxVLDataSEXP, SEXP baseRandEffDMSEXP, SEXP fzDataSEXP, SEXP conscSEXP, SEXP consrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type xAIDS(xAIDSSEXP);
    Rcpp::traits::input_parameter< const double& >::type maxDTime(maxDTimeSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type betaAIDS(betaAIDSSEXP);
    Rcpp::traits::input_parameter< const double& >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type bFE(bFESEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type varCovRE(varCovRESEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type baseCD4DM(baseCD4DMSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type fxCD4Data(fxCD4DataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type baseVLDM(baseVLDMSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type fxVLData(fxVLDataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type baseRandEffDM(baseRandEffDMSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type fzData(fzDataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type consc(conscSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type consr(consrSEXP);
    rcpp_result_gen = Rcpp::wrap(PostWCpp(w, y, xAIDS, maxDTime, betaAIDS, kappa, bFE, sigma2, varCovRE, baseCD4DM, fxCD4Data, baseVLDM, fxVLData, baseRandEffDM, fzData, consc, consr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hivPlatform_integrate_test", (DL_FUNC) &_hivPlatform_integrate_test, 0},
    {"_hivPlatform_PostWCpp", (DL_FUNC) &_hivPlatform_PostWCpp, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_hivPlatform(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
